<?php
/**
 * 定数定義ファイル
 */

//----------------------
// ユーザー画面
//----------------------

/*
 * サブスク
 */
define( 'BASE_SUMBNAIL', 'http://img.youtube.com/vi/%s/mqdefault.jpg' ); // 動画サムネイル

//----------------------
// 管理画面
//----------------------
define( 'VIEW_GENERAL', '1' );		// 一般画面
define( 'VIEW_INTRODUCTION', '2' );	// 紹介画面
define( 'VIEW_LP', '3' );			// LP画面
define( 'VIEW_SUBSCRIPTION', '4' );	// サブスク画面


?>
