<?php
/**
 * DB接続情報
 */

// MAMP起動用
const DB_HOST		= '127.0.0.1';
const DB_PORT		= '5432';
const DB_NAME		= 'postgres';
const DB_USER		= 'user';
const DB_PASS		= 'user';
const DB_STRING		= 'host=%s port=%s dbname=%s user=%s password=%s';

// AWS
/*
const DB_HOST		= 'database-1.cawjcwmqlgjp.ap-northeast-1.rds.amazonaws.com'; // RDSエンドポイント
const DB_PORT		= '5432';
const DB_NAME		= 'postgres';
const DB_USER		= 'postgres';
const DB_PASS		= 'dot-garage';
const DB_STRING		= 'host=%s port=%s dbname=%s user=%s password=%s';
*/
?>
